#!/usr/bin/env bash
# scripts that displays information about subdomains

# Function to get information about a subdomain
domain_info() {
    local domain="$1"
    local subdomain="$2"
    local line
    line=$(dig +short "$subdomain.$domain")
    if [ -z "$line" ]; then
        echo "The subdomain $subdomain does not have an associated IP address."
    else
        echo "The subdomain $subdomain is an A record and points to $line"
    fi
}

# Check the number of command-line arguments
if [ "$#" -eq 1 ]; then
    # If there is only one argument, assume it's the domain
    domain="$1"
    domain_info "$domain" "www"
    domain_info "$domain" "lb-01"
    domain_info "$domain" "web-01"
    domain_info "$domain" "web-02"
elif [ "$#" -eq 2 ]; then
    # If there are two arguments, assume the first is the domain and the second is the subdomain
    domain="$1"
    subdomain="$2"
    domain_info "$domain" "$subdomain"
else
    # If the number of arguments is not 1 or 2, display usage information
    echo "Usage: $0 <domain> [subdomain]"
fi
