#!/usr/bin/env bash
# Install nginx on your web-01

# update package list on the remote sever
ssh ubuntu@52.86.114.220 "sudo apt update"

# install nginx on the remote server
ssh ubuntu@52.86.114.220 "sudo apt install -y nginx"

# create a default nginx configuration file on the remote server
ssh ubuntu@52.86.114.220 "sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html"

# Test Nginx
ssh ubuntu@52.86.114.220 "sudo nginx -t"

# Restart Nginx on the remote server (without using systemctl)
ssh ubuntu@52.86.114.220 "sudo service ngninx restart" 
