#!/usr/bin/env bash
# Install nginx on your web-01

# update package list on the remote sever
sudo apt update

# install nginx on the remote server
sudo apt install -y nginx

# create a default nginx configuration file on the remote server
sudo bash -c "echo 'Hello World!' > /var/www/html/index.html"

# Test Nginx
sudo nginx -t

# Restart Nginx on the remote server (without using systemctl)
sudo service nginx restart
