#!/usr/bin/env bash
# configuring nginx to direct on another page
sudo apt-get update -y
sudo apt-get install nginx -y

echo 'Ceci n'est pas une page' | sudo tee /var/www/html/index.html

replace="server_name _;\n\trewrite ^\/axy https:\/\/genarts.tech/ permanent;"

sudo sed -i "s/server_name _;/$replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart