#!/usr/bin/env bash

# Replace STUDENT_ID with your actual student ID
STUDENT_ID="306856"

# Install HAProxy
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get -y install haproxy

# Enable HAProxy
sudo sed -i -e 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOL
listen http-in
  bind :80
  balance roundrobin
  server ${STUDENT_ID}-web-01 [IP_OF_WEB_01]:80 check
  server ${STUDENT_ID}-web-02 [IP_OF_WEB_02]:80 check
EOL

# Restart HAProxy
sudo service haproxy restart
