#!/usr/bin/env bash
# Configure HAProxy 

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver web-01 52.86.114.220:80 check\n\tserver web-02 52.3.254.18:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
