#!/usr/bin/env bash
# Configure HAProxy

# Update package list and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Define the HAProxy configuration on a backend server
server_config=\
"
backend patrickkabanda_backend
    balance roundrobin
    mode http
    server 306856-web-01 52.86.114.220:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Check HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply changes
sudo service haproxy restart

# Provide feedback
echo "HAProxy is successfully installed and configured."
