#!/usr/bin/env bash
# nginx configuration server to port 80 but in short way
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx stop
sudo service nginx start
